Start of adding initializations to project flow
Having issues with the backpropagation from the loss.backwards(), error message reads as follows:

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

If you guys have any ideas please give your input